-- Application user provisioning
DO
$do$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'app_user') THEN
      CREATE USER app_user WITH ENCRYPTED PASSWORD 'AppUserSecure2026!';
   ELSE
      ALTER USER app_user WITH ENCRYPTED PASSWORD 'AppUserSecure2026!';
   END IF;
END
$do$;

GRANT CONNECT ON DATABASE fx_orders_db TO app_user;
GRANT USAGE, CREATE ON SCHEMA public TO app_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app_user;
